# Generated by Django 4.2.6 on 2024-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('adhar_number', models.CharField(max_length=12, unique=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('assigned_mobile_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('Platinum365', 'Platinum365'), ('Gold180', 'Gold180'), ('Silver90', 'Silver90')], max_length=20)),
                ('plan_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('validity_days', models.IntegerField()),
                ('plan_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('expiry_date', models.DateField(default=None, null=True)),
            ],
        ),
    ]
